/**
 * @file ui.h
 * @brief User Interface header for MetalDetector project generated by SquareLine Studio.
 *
 * This file contains the declarations for user interface components and functions
 * used in the MetalDetector project. It includes constants, data structures, and
 * function prototypes for managing and displaying the user interface using LVGL.
 *
 * Created on: Jul 30, 2024
 * Author: Viktor
 */

#ifndef _METALDETECTOR_UI_H
#define _METALDETECTOR_UI_H

#include "lvgl.h"

/** @brief Length of the time domain chart. */
#define TIME_DOMAIN_CHART_LEN                    100

/** @brief Length of the frequency domain chart. */
#define FREQ_DOMAIN_CHART_LEN                    256

/** @brief Maximum value for the time domain chart. */
#define TIME_DOMAIN_MAX_VALUE                    4095

/** @brief Maximum value for the frequency domain chart. */
#define FREQ_DOMAIN_MAX_VALUE                    1000

/**
 * @brief Enumeration for chart domains.
 */
typedef enum
{
    CHART_TIME_DOMAIN = 0,     /*!< Time domain chart */
    CHART_FREQ_DOMAIN          /*!< Frequency domain chart */
} UI_ChartDomains_t;

extern UI_ChartDomains_t ui_chart_domain;    /*!< Current chart domain */

/* LVGL object declarations */
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Tab;
extern lv_obj_t * ui_MainTab_;
extern lv_obj_t * ui_PhaseMainPanel;
extern lv_obj_t * ui_PhaseArc;
extern lv_obj_t * ui_PhaseDecorSircle;
extern lv_obj_t * ui_PhaseLabel;
extern lv_obj_t * ui_DepthPanel;
extern lv_obj_t * ui_DepthBar;
extern lv_obj_t * ui_DepthLabel;
extern lv_obj_t * ui_SettingsTab_;
extern lv_obj_t * ui_GndBalancePanel;
extern lv_obj_t * ui_GndBalanceConf;
extern lv_obj_t * ui_GndBalanceLabel;
extern lv_obj_t * ui_GndBalanceButton;
extern lv_obj_t * ui_GndBalanceBtnLabel;
extern lv_obj_t * ui_GndBalanceVal;
extern lv_obj_t * ui_SensPanel;
extern lv_obj_t * ui_SensConf_;
extern lv_obj_t * ui_SensLabel;
extern lv_obj_t * ui_SenseVal;
extern lv_obj_t * ui_ChartDomainDropdown;
extern lv_obj_t * ui_ChartTab_;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_Chart_Xaxis;
extern lv_obj_t * ui_Chart_Yaxis1;
extern lv_obj_t * ui_Chart_Yaxis2;
extern lv_chart_series_t * ui_Chart_series_1;
extern lv_chart_series_t * ui_Chart_series_2;
extern lv_obj_t * ui____initial_actions0;

/**
 * @brief Initialize the user interface.
 */
void ui_init(void);

#endif /* _METALDETECTOR_UI_H */



